adjective1 = input("Enter an adjective (description, quality): ")
noun1 = input("Enter a noun (name, place, thing): ")
adjective2 = input("Enter an adjective (description, quality): ")
verb1 = input("Enter the verb ending with 'ing': ")
adjective3 = input("Enter an adjective (description, quality): ")

print(f"Today I went to a {adjective1} zoo.")
print(f"In an exhibit, I saw {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was {adjective3}!")